baseURL = "https://techblog.operant.io"
languageCode = "en"
defaultContentLanguage = "en"
theme = "KeepIt"

[Languages]
  [Languages.en]
    title = "techblog.operant.io"
    weight = 0

paginate = 12
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = "UA-73276509-3"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.blackfriday]
    hrefTargetBlank = true
    nofollowLinks = true
    noreferrerLinks = true
  [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true
    autoHeadingIDType = "github"

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    name = "Tribe of Hackers"
    url = "/toh"
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[params]
    since = 2020
    author = "@operant"               # Author's name
    subtitle = "Hi, I'm Dave. Follow me on the platforms below, and check out my latest posts."       # Subtitle
    cdn_url = "https://master.d2b7bvt8n689h2.amplifyapp.com/"           # Base CDN URL
    home_mode = "" # post or other
    git_url = "https://github.com/0xOperant/techblog.operant.io"

    google_verification = ""
    bing_verification = ""
    yandex_verification = ""
    pinterest_verification = ""
    baidu_verification = ""

    avatar = "/images/me/avatar.png" #comment it to use gravatar
    socialShare = true

    description = "Sharing my experiences as a Red Team leader" # site description
    keywords = "tech, red team, cyber, infosec, security" # site keywords
    images = ["https://master.d2b7bvt8n689h2.amplifyapp.com/cover.png"]

    license= 'Licensed under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>, except where marked (with &copy;). Some rights reserved.'

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[params.social]
    GitHub = "0xOperant"
    Linkedin = "belldavidr"
    Twitter = "operant"
    #Instagram = "xxxx"
    #Email   = "xxxx"
    #Facebook = "xxxx"
    #Telegram = "xxxx"
    #Medium = "xxxx"
    #Gitlab = "xxxx"
    #Youtubelegacy = "xxxx"
    #Youtubecustom = "xxxx"
    #Youtubechannel = "xxxx"
    #Tumblr ="xxxx"
    #Quora = "xxxx"
    Keybase = "belldavidr"
    #Pinterest = "xxxx"
    Reddit = "0xOperant"
    #Codepen = "xxxx"
    Bitbucket = "belldavidr"
    #Stackoverflow = "xxxxx"
    #Weibo = "xxxx"
    #Odnoklassniki = "xxxx"
    #VKontakte = "xxxx"
    #Flickr = "xxxx"
    #Xing = "xxxx"
    #Snapchat = "xxxx"
    #Soundcloud = "xxxx"
    #Spotify = "xxxx"
    #Bandcamp = "xxxx"
    #Paypal = "xxxx"
    #Fivehundredpx = "xxxx"
    #Mix = "xxxx"
    #Goodreads = "xxxx"
    #Lastfm = "xxxx"
    #Foursquare = "xxxx"
    #Hackernews = "0xoperant"
    #Kickstarter = "xxxx"
    #Patreon = "xxxx"
    #Steam = "xxxx"
    #Twitch = "xxxx"
    #Strava = "xxxx"
    #Skype = "xxxx"
    #Whatsapp = "xxxx"
    #Zhihu = "xxxx"
    #Douban = "xxxx"
    #Angellist = "xxxx"
    #Slidershare = "xxxx"
    #Jsfiddle = "xxxx"
    #Deviantart = "xxxx"
    #Behance = "xxxx"
    #Dribble = "xxxx"
    #Wordpress = "xxxx"
    #Vine = "xxxx"
    #Googlescholar = "xxxx"
    #Researchgate = "xxxx"
    Mastodon = "@operant"
    #Thingiverse = "xxxx"

[params.share]
Twitter = true
Facebook = true
Reddit = true
Linkedin = true
Pinterest = true
HackerNews = true
#Mix = true
Tumblr = true
#VKontakte = true
#Douban = true
#Weibo = true

# Used only for Seo schema
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "@operant"

  [params.publisher]
    name = "@operant"

    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  [params.logo]
    url = "logo.png"
    width = 127
    height = 40

  [params.image]
    url = "cover.png"
    width = 800
    height = 600

[params.utterances]                  # https://utteranc.es/
    owner = "0xOperant"              # Your GitHub ID
    repo  = "techblog.operant.io"    # The repo to store comments
    theme = "github-light"
